workspace:
  base: /go
  path: src/github.com/cicd-hackathon-stgt/droneio


pipeline: 
  buildGo: 
    image: golang 
    commands: 
      - go build . 

  buildDocker:
    image: docker
    commands:
      - docker build --rm -t zanetworker/hello-world .
      - docker run --rm octocat/hello-world --test
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock