pipeline:

  install:
    image: node:6
    commands:
      - npm install

  test:
    group: test
    image: node:6
    commands:
      - npm run test

  frontend:
    group: test
    image: node:6
    commands:
      - npm run build

  execute:
    image: node:6
    commands:
      - ./droneio
