workspace:
  base: /go
  path: src/github.com/cicd-hackathon-stgt/droneio

pipeline:
  go_test:
    group: test
    image: golang
    commands:
      - go get
      - go build -v
      - go test -v -race

  python_test:
    group: test
    image: python
    commands:
      - pip install django

  docker:
    image: plugins/docker
    repo: cicd-hackathon-stgt/droneio
    tags: [ latest ]
    registry: null

  run_go:
    image: golang
    commands:
      - go get
      - go build -v
      - ./droneio
