pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - .npm-cache
    volumes:
      - /tmp/cache:/cache

  main:
    image: geekykaran/headless-chrome-node-docker
    commands:
      - npm config set cache .npm-cache
      - npm install
      - npm test

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - .npm-cache
    volumes:
      - /tmp/cache:/cache
