workspace:
  base: /go
  path: src/github.com/cicd-hackathon-stgt/droneio

pipeline:
  go_test:
    group: test
    image: golang
    commands:
      - go get
      - go build -v
      - go test -v -race

  python_test:
    group: test
    image: python
    commands:
      - pip install django

  build:
    image: docker
    commands:
      - docker build --rm -t cicd-hackathon-stgt/droneio:latest .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  run_go:
    image: cicd-hackathon-stgt/droneio:latest
