workspace:
  base: /go
  path: src/github.com/cicd-hackathon-stgt/droneio

pipeline:
  test:
    group: go
    image: golang:1.10
    commands:
      - sleep 10
      - go test -v -race

  build:
    group: go
    image: golang:1.10
    commands:
      - sleep 10
      - go build -v

  docker:
    image: plugins/docker
    repo: cicd-hackathon-stgt/droneio
    tags: [ latest ]
    secrets: [ docker_username, docker_password ]

  execute:
    image: golang
    commands:
      - ./droneio
