workspace:
  base: /go
  path: src/github.com/cicd-hackathon-stgt/droneio

pipeline:
  test:
    group: go
    image: golang:1.6
    commands:
      - go test -v -race

  build:
    group: go
    image: golang:1.10
    commands:
      - go build -v

  execute:
    image: golang
    commands:
      - ./droneio
