workspace:
  base: /go
  path: src/github.com/cicd-hackathon-stgt/droneio


pipeline: 
  buildGo: 
    image: golang 
    commands: 
      - go build . 

  buildDocker:
    image: docker
    commands:
      - docker build --rm -t zanetworker/hello-drone .
      - docker run --rm zanetworker/hello-drone --test
    volumes: 
      - /var/run/docker.sock:/var/run/docker.

  buildNestedDocker:
    image: docker
    commands:
      - docker build -f Dockerfile.depends --rm -t zanetworker/child-drone.
      - docker run --rm zanetworker/child-drone --test
    volumes: 
      - /var/run/docker.sock:/var/run/docker.

  
  