pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  install:
    image: geekykaran/headless-chrome-node-docker
    commands:
      - npm install

  test:
    image: geekykaran/headless-chrome-node-docker
    commands:
      - npm test

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
