workspace:
  base: /go
  path: src/github.com/cicd-hackathon-stgt/droneio

pipeline:
  go_test:
    group: test
    image: golang
    commands:
      - go get
      - go build -v
      - go test -v -race

  python_test:
    group: test
    image: python
    commands:
      - pip install django

  run_go:
    image: golang
    commands:
      - go get
      - go build -v
      - ./droneio

  slack:
    image: plugins/slack
    channel: C9H9DP8N5
    webhook: https://hooks.slack.com/services/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
