workspace:
  base: /go
  path: src/github.com/cicd-hackathon-stgt/droneio

pipeline:
  build: 
    image: golang
    commands: 
      - go build . 
    
  docker:
    image: plugins/docker
    repo: zanetworker/droneio
    tags: [ 'latest' ]
