workspace:
  base: /go
  path: src/github.com/cicd-hackathon-stgt/droneio


pipeline: 
  buildGo: 
    image: golang 
    commands:
      - go build . 

  buildDocker:
    image: docker
    commands:
      - docker build --rm -t ${parent_image} .
      - docker run --rm ${parent_image}
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock

  buildNestedDocker:
    image: docker
    commands:
      - docker build -f Dockerfile.depends --rm -t ${child_image} .
      - docker run --rm ${child_image}
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock 


  pushToArtifactory: 
    image: docker 
    commands: 
    - docker login hohcicd-docker.jfrog.io -u ${artifactory_user} -p ${artifactory_pass}
    - docker tag ${parent_image} ${artifactory_repo_tag}/${parent_image}:latest
    - docker tag ${child_image} ${artifactory_repo_tag}/${child_image}:latest
    - docker push ${artifactory_repo_tag}/${parent_image}:latest
    - docker push ${artifactory_repo_tag}/${child_image}:latest
    
    volumes: 
    - /var/run/docker.sock:/var/run/docker.sock 
  cleanUpDockerImages: 
     image: docker 
     commands: 
       - docker rmi ${parent_image} 
       - docker rmi ${child_image}
     volumes: 
      - /var/run/docker.sock:/var/run/docker.sock 

  
matrix:
  parent_image:
   - zanetworker/hello-drone
  child_image: 
   - zanetworker/child-drone
  artifactory_repo_tag: 
   - hohcicd-docker.jfrog.io
  artifactory_user: 
   - droneio
  artifactory_pass: 
   - droneior0cks
 