pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  install:
    image: geekykaran/headless-chrome-node-docker
    commands:
      - npm install

  test:
    image: geekykaran/headless-chrome-node-docker
    commands:
      - npm test

  build:
    image: geekykaran/headless-chrome-node-docker
    commands:
      - npm run build

  npm_auth:
    image: robertstettner/drone-npm-auth
    secrets: [ npm_username, npm_password, npm_email ]

  publish:
    when:
      event: tag
    image: geekykaran/headless-chrome-node-docker
    commands:
      - npm publish --access public

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
